version: "3"
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    env_file: ./db.env
    volumes:
      - ./db/db_data:/var/lib/postgresql/data

  app:
    build: ./app
    depends_on: 
      - db
    volumes:
      - ./app:/app
    env_file: ./app.env
    environment:
      APP_DB_HOST: db
    command: python src/main.py